#pragma checksum "..\..\..\..\..\..\..\..\Signup.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "396312B37E53E70F769CF1BA48A986D5A719BDE98F1133F77BF3AC495821CF44"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MaterialDesignThemes.Wpf;
using MaterialDesignThemes.Wpf.Converters;
using MaterialDesignThemes.Wpf.Transitions;
using OysterVPN;
using SharpVectors.Converters;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace OysterVPN {
    
    
    /// <summary>
    /// Signup
    /// </summary>
    public partial class Signup : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 69 "..\..\..\..\..\..\..\..\Signup.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtEmailAddress;
        
        #line default
        #line hidden
        
        
        #line 99 "..\..\..\..\..\..\..\..\Signup.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox txtPassword;
        
        #line default
        #line hidden
        
        
        #line 123 "..\..\..\..\..\..\..\..\Signup.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox txtRePassword;
        
        #line default
        #line hidden
        
        
        #line 138 "..\..\..\..\..\..\..\..\Signup.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox checkBoxTerms;
        
        #line default
        #line hidden
        
        
        #line 145 "..\..\..\..\..\..\..\..\Signup.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtValidate;
        
        #line default
        #line hidden
        
        
        #line 151 "..\..\..\..\..\..\..\..\Signup.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSignup;
        
        #line default
        #line hidden
        
        
        #line 160 "..\..\..\..\..\..\..\..\Signup.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid SignupLoadingGrid;
        
        #line default
        #line hidden
        
        
        #line 163 "..\..\..\..\..\..\..\..\Signup.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Viewbox SignupLoadingBar;
        
        #line default
        #line hidden
        
        
        #line 172 "..\..\..\..\..\..\..\..\Signup.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BackToLogin;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/OysterVPN;component/signup.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\..\..\..\Signup.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.txtEmailAddress = ((System.Windows.Controls.TextBox)(target));
            
            #line 69 "..\..\..\..\..\..\..\..\Signup.xaml"
            this.txtEmailAddress.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.txtEmailAddress_TextChanged_1);
            
            #line default
            #line hidden
            return;
            case 2:
            this.txtPassword = ((System.Windows.Controls.PasswordBox)(target));
            return;
            case 3:
            this.txtRePassword = ((System.Windows.Controls.PasswordBox)(target));
            return;
            case 4:
            this.checkBoxTerms = ((System.Windows.Controls.CheckBox)(target));
            
            #line 138 "..\..\..\..\..\..\..\..\Signup.xaml"
            this.checkBoxTerms.Checked += new System.Windows.RoutedEventHandler(this.checkBoxTerms_Checked);
            
            #line default
            #line hidden
            return;
            case 5:
            this.txtValidate = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.btnSignup = ((System.Windows.Controls.Button)(target));
            
            #line 151 "..\..\..\..\..\..\..\..\Signup.xaml"
            this.btnSignup.Click += new System.Windows.RoutedEventHandler(this.btnSignup_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.SignupLoadingGrid = ((System.Windows.Controls.Grid)(target));
            return;
            case 8:
            this.SignupLoadingBar = ((System.Windows.Controls.Viewbox)(target));
            return;
            case 9:
            this.BackToLogin = ((System.Windows.Controls.Button)(target));
            
            #line 172 "..\..\..\..\..\..\..\..\Signup.xaml"
            this.BackToLogin.Click += new System.Windows.RoutedEventHandler(this.BackToLogin_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

